version: 2
project_name: pipolinkcheck

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.Version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}

binary_signs:
  - id: code-sign
    cmd: sh
    args:
      - "-c"
      - "./scripts/sign.sh '${artifact}'"
    env:
      - WINDOWS_SIGNING_PFX={{ envOrDefault "WINDOWS_SIGNING_PFX" "" }}
      - WINDOWS_SIGNING_PASSWORD={{ envOrDefault "WINDOWS_SIGNING_PASSWORD" "" }}
      - MACOS_SIGNING_IDENTITY={{ envOrDefault "MACOS_SIGNING_IDENTITY" "" }}
    artifacts: binary

checksum:
  name_template: 'checksums.txt'

changelog:
  use: git
  format: "{{ .Message }}"

release:
  github:
    owner: jlettori
    name: pipolinkcheck
