// Code generated by "stringer -linecomment -type=ErrorCode"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[errCodeUnauthorized-401]
	_ = x[errCodeForbidden-403]
	_ = x[errCodeNotFound-404]
	_ = x[errCodeTooManyRequests-429]
	_ = x[errCodeInternalServerError-500]
	_ = x[errCodeBadGateway-502]
	_ = x[errCodeServiceUnavailable-503]
	_ = x[errCodeGatewayTimeout-504]
	_ = x[errCodeLinkedInDenied-999]
	_ = x[errCodeRequestConstruction-1001]
	_ = x[errCodeRequestFailed-1002]
	_ = x[errCodeProcessingPanic-1003]
}

const (
	_ErrorCode_name_0 = "Unauthorized"
	_ErrorCode_name_1 = "ForbiddenNot Found"
	_ErrorCode_name_2 = "Too Many Requests"
	_ErrorCode_name_3 = "Internal Server Error"
	_ErrorCode_name_4 = "Bad GatewayService UnavailableGateway Timeout"
	_ErrorCode_name_5 = "LinkedIn denied the request"
	_ErrorCode_name_6 = "building the HTTP request failedthe HTTP request could not be completedprocessing the link panicked"
)

var (
	_ErrorCode_index_1 = [...]uint8{0, 9, 18}
	_ErrorCode_index_4 = [...]uint8{0, 11, 30, 45}
	_ErrorCode_index_6 = [...]uint8{0, 32, 71, 99}
)

func (i ErrorCode) String() string {
	switch {
	case i == 401:
		return _ErrorCode_name_0
	case 403 <= i && i <= 404:
		i -= 403
		return _ErrorCode_name_1[_ErrorCode_index_1[i]:_ErrorCode_index_1[i+1]]
	case i == 429:
		return _ErrorCode_name_2
	case i == 500:
		return _ErrorCode_name_3
	case 502 <= i && i <= 504:
		i -= 502
		return _ErrorCode_name_4[_ErrorCode_index_4[i]:_ErrorCode_index_4[i+1]]
	case i == 999:
		return _ErrorCode_name_5
	case 1001 <= i && i <= 1003:
		i -= 1001
		return _ErrorCode_name_6[_ErrorCode_index_6[i]:_ErrorCode_index_6[i+1]]
	default:
		return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
