// Code generated by "stringer -linecomment -type=LinkType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LinkTypeHyperlink-0]
	_ = x[LinkTypeImage-1]
	_ = x[LinkTypeCSS-2]
	_ = x[LinkTypeScript-3]
	_ = x[LinkTypeVideo-4]
}

const _LinkType_name = "hyperlinkimagecssscriptvideo"

var _LinkType_index = [...]uint8{0, 9, 14, 17, 23, 28}

func (i LinkType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LinkType_index)-1 {
		return "LinkType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LinkType_name[_LinkType_index[idx]:_LinkType_index[idx+1]]
}
